### ISSUE TITLE
GUI for installation

### ISSUE THREAD

**Issue by kcalvinalvin** [fort-nix/nix-bitcoin#100]
It would be nice to have a GUI for installation. The installer would be aware of configuration.nix and be able to make changes to that. The FIXMEs would be taken care of the GUI installer.

Based on [this](https://github.com/NixOS/nixpkgs/issues/21662) issue, seems like no one is really working on it. 

Anyone here working on it?

**Comment by nixbitcoin** [comment]
Yes, we have thought about that, but in the past we have agreed that right now nix-bitcoin should stay focused on its strengths: bringing security and reliability to an expert audience. 

A GUI would be nice though because it could recognize the dependencies between FIXMEs and guide the user through configuration. It could also be a simple bash wizard or console-based config interface that automatically edits the FIXME's with sed.

One big problem for getting nix-bitcoin into the hands of more novice users is also that we have yet to figure out a way to distribute updates reliably through git without requiring some kind of familiarity with manually merging git commits on the user's part.

**Comment by jb55** [comment]
> One big problem for getting nix-bitcoin into the hands of more novice users is also that we have yet to figure out a way to distribute updates reliably through git without requiring some kind of familiarity with manually merging git commits on the user's part

nixos can be pretty flexible in this regard. here's an example of a recent project I did where git pushs would update the revision hash and switch to a new system state: https://jb55.com/s/2dd8d12cd0165a5c.txt

obviously this is a super hack but it demonstrates how dynamic updates could be. For a casa-like system, updates would just be nixos-rebuilds with the latest git revision. You would need to write some system service/web frontend to manage git pulls, etc. it wouldn't be too hard, but it's a decent amount of work.

**Comment by kcalvinalvin** [comment]
How would a simple GUI with PyQt be? Just edit the configuration.nix file with sed. Doesn't seem that difficult.

**Comment by nixbitcoin** [comment]
We should take another look at this, especially because we have the new release process now.

In my opinion we should harden and stabilize the code first, and then implement usability improvements like this.

**Comment by nixbitcoin** [comment]
This is out-of-scope for the core nix-bitcoin project.
