### ISSUE TITLE
Node discovery

### ISSUE THREAD

**Issue by tyrion** [fort-nix/nix-bitcoin#329]
I have a few doubts about how node discovery works in nix-bitcoin. Forgive me if these are trivial questions but I could not find them answered anywhere.

There is a default `addnode=ecoc5q34tmbq54wl.onion`. *What is that tor node? Is that node the only way in which nix-bitcoin, by default, discovers other nodes?* According to my understanding, that could be a problem if I do not trust that node.

Moreover, nix-bitcoin is running, by default, behind Tor, and I guess the purpose is not to make obvious to the ISP that one is running a bitcoin node (because if we only wanted to broadcast our transactions anonymously [we would not need to run the whole node behind tor][1]). Then, *why the `dns` and `dnsseed` options are not disabled? Couldn't this leed to leaking information through dns queries?* Or are these queries, by default, routed through tor as well?

Thank you

[1]: https://bitcoin.stackexchange.com/a/99468/109163

**Comment by jonasnick** [comment]
Hi @tyrion!

> What is that tor node?

It's one of my nodes. The reason that it's there is mostly historic. When I started with nix-bitcoin I wanted my nodes to connect to each other. There shouldn't be a downside to having this additional peer. A (probably rather minor) benefit is that the [Bitcoin over Tor isn't a good idea](https://arxiv.org/pdf/1410.6079)-attack is more difficult (iirc) because my node runs both on Tor and clearnet.

> Is that node the only way in which nix-bitcoin, by default, discovers other nodes?

Bitcoin should still use the default peer discovery mechanisms. `-addnode` simply adds an additional node on top of whatever bitcoind decides to do which also means that it doesn't use up an outbound connection slot. Yes it would be a problem & a bug if that node was in any way trusted to provide peers to connect to.

> Then, why the dns and dnsseed options are not disabled? Couldn't this leed to leaking information through dns queries? Or are these queries, by default, routed through tor as well?

Bitcoin Core's [tor.md](https://github.com/bitcoin/bitcoin/blob/master/doc/tor.md) mentions

> Note: Only the -proxy option sets the proxy for DNS requests;
> with -onion they will not route over Tor, so use -proxy if you
> have privacy concerns.

which implies that DNS queries are proxied through tor in nix-bitcoin. Moreover, if you run the secure-node preset then the bitcoin service can only send ip packets to localhost (c.f. "enforceTor").

**Comment by tyrion** [comment]
Thank you for the great reply!
