### ISSUE TITLE
hidepid module removed with groups-v2 - add a toggle for it?

### ISSUE THREAD

**Issue by colemickens** [fort-nix/nix-bitcoin#342]
Hi. I am trying to experiment with `btcpayserver`  and thought I'd try to use this repo's module instead of writing my own.

However, my system is using cgroups-v2. Even if I try to lib.mkForce disable hideProcessInformation, I still get a fatal error about it.

Would you merge a toggle that allowed me to disable this in the secure node preset?

**Comment by erikarvstedt** [comment]
The config setting `nix-bitcoin.security.hideProcessInformation = lib.mkForce false;` completely disables this option, so the error might have a different cause.
What exact error message are you getting?

**Comment by colemickens** [comment]
Ah, yes, it's more that the option has been forcibly removed:

```
error: The option `security.hideProcessInformation' can no longer be used since it's been removed. The hidepid module was removed, since the underlying machinery
       is broken when using cgroups-v2.
(use '--show-trace' to show detailed location information)
```

so it's just not valid anymore. I guess this is because I'm using nixos-unstable?

It's unfortunate that it's an error even if forcing the option to false.

**Comment by nixbitcoin** [comment]
Are you sure you're setting `nix-bitcoin.security.hideProcessInformation = lib.mkForce false;` not `security.hideProcessInformation = lib.mkForce false;`? We're wrapping the NixOS option in our own option in https://github.com/fort-nix/nix-bitcoin/blob/c051544d464439a7f72f31131b6d3e676d218e18/modules/security.nix#L5

**Comment by erikarvstedt** [comment]
@nixbitcoin, our `security.nix` module strictly depends on NixOS' `security.hideProcessInformation` which has been removed on unstable. I'll add a fix later today.

**Comment by nixbitcoin** [comment]
On 18.03.2021 11:37, erikarvstedt wrote:
***@***.***, our `security.nix` module strictly depends on NixOS' `security.hideProcessInformation` which has been removed on unstable. I'll add a fix later today.

Ok, sounds good. I'll review.

--
nixbitcoindev [DD11 F9AD 5308 B3BA]
Use PGP

**Comment by erikarvstedt** [comment]
Due to the many breaking changes in NixOS unstable, making `nix-bitcoin` compatible with both NixOS stable and unstable would take too much effort.
Instead, I've added branch [nixos-unstable](https://github.com/erikarvstedt/nix-bitcoin/tree/nixos-unstable) in my fork. 
The following lower-priority features haven't yet been fixed and are disabled:
- `services.clightning.plugins.prometheus` (build failure)
- `services.liquidd` (build failure)
- `services.joinmarket-ob-watcher` (service failure)
- `nix-bitcoin.netns-isolation` (service failure)

@colemickens, let us know if you require any of these features.

@jonasnick, if you add this branch to `nix-bitcoin`, it could serve as a base for working on compatibility with the upcoming NixOS release.

**Comment by jonasnick** [comment]
@erikarvstedt That's great work. Pushed a nixos-unstable branch that allows opening PRs against it.

**Comment by nixbitcoin** [comment]
@colemickens can you confirm this is working so we can close the issue?

**Comment by erikarvstedt** [comment]
@colemickens, I'm keeping this PR (https://github.com/fort-nix/nix-bitcoin/pull/344) updated for unstable support.

**Comment by jonasnick** [comment]
nix-bitcoin doesn't set `security.hideProcessInformation` anymore since #374 was merged. Does that solve this issue?

**Comment by nixbitcoin** [comment]
Yes
