### ISSUE TITLE
Bitcoin Core 18.0 Update

### ISSUE THREAD

**Issue by 0xB10C** [fort-nix/nix-bitcoin#60]
With the recent release of [Bitcoin Core 18.0](https://lists.linuxfoundation.org/pipermail/bitcoin-core-dev/2019-May/000078.html): What is the nix-bitcoin update schedule for things like Bitcoin Core and e.g. c-lightning? 

How could one help to update Bitcoin Core in nix-bitcoin?

**Comment by jonasnick** [comment]
The way this normally happens is that one of the maintainers of the Bitcoin package (usually Russell O'Connor, who works at Blockstream) will create a PR with the update to https://github.com/NixOS/nixpkgs/pulls (see for example https://github.com/NixOS/nixpkgs/pull/52868). We will then get the update by update our pinned nix packages. Since this is not a time critical release fixing a security issue, this is my preferred way of doing this. Alternatively, we could create and maintain our own package in nix-bitcoin that we try to update faster.

**Comment by 0xB10C** [comment]
Thanks for clarification. Agreeing that there is no hurry to update for 18.0. Just curious about the process.

**Comment by jonasnick** [comment]
fwiw opening the PR to nixpkgs should happen within the next few days.

**Comment by jonasnick** [comment]
https://github.com/NixOS/nixpkgs/pull/60848

**Comment by 0xB10C** [comment]
[NixOS/nixpkgs#60848](https://github.com/NixOS/nixpkgs/pull/60848) is now merged.
