### ISSUE TITLE
Incorrect password attempt from 127.0.0.1

### ISSUE THREAD

**Issue by stevenroose** [fort-nix/nix-bitcoin#85]
I'm getting a ton of these log messages in my bitcoind logs:
```
Jul 10 08:53:20 dasilva-nix bitcoind[31937]: 2019-07-10T08:53:20Z ThreadRPCServer incorrect password attempt from 127.0.0.1:51402
Jul 10 08:53:20 dasilva-nix bitcoind[31937]: 2019-07-10T08:53:20Z ThreadRPCServer incorrect password attempt from 127.0.0.1:51406
Jul 10 08:53:20 dasilva-nix bitcoind[31937]: 2019-07-10T08:53:20Z ThreadRPCServer incorrect password attempt from 127.0.0.1:51412
Jul 10 08:53:20 dasilva-nix bitcoind[31937]: 2019-07-10T08:53:20Z ThreadRPCServer incorrect password attempt from 127.0.0.1:51418
Jul 10 08:53:21 dasilva-nix bitcoind[31937]: 2019-07-10T08:53:21Z ThreadRPCServer incorrect password attempt from 127.0.0.1:51420
Jul 10 08:53:21 dasilva-nix bitcoind[31937]: 2019-07-10T08:53:21Z ThreadRPCServer incorrect password attempt from 127.0.0.1:51426
Jul 10 08:53:21 dasilva-nix bitcoind[31937]: 2019-07-10T08:53:21Z ThreadRPCServer incorrect password attempt from 127.0.0.1:51438
Jul 10 08:53:22 dasilva-nix bitcoind[31937]: 2019-07-10T08:53:22Z ThreadRPCServer incorrect password attempt from 127.0.0.1:51442
Jul 10 08:53:22 dasilva-nix bitcoind[31937]: 2019-07-10T08:53:22Z ThreadRPCServer incorrect password attempt from 127.0.0.1:51446
Jul 10 08:53:22 dasilva-nix bitcoind[31937]: 2019-07-10T08:53:22Z ThreadRPCServer incorrect password attempt from 127.0.0.1:51452
```

Would this be the clightning node trying to connect to bitcoind with a wrong password? Or electrs?

**Comment by nixbitcoin** [comment]
I'm running clightning and electrs, and don't get any of these error messages. Have you made any other modifications beside https://github.com/fort-nix/nix-bitcoin/issues/86? @jonasnick any ideas?

**Comment by nixbitcoin** [comment]
I just now got this issue when updating my node and having the secrets files temporarily out of sync. My mistake was that I quit the `nix-shell` command prematurely because it was taking too long because of limited entropy on my system.

Try deleting your `~/my-nix-bitcoin/secrets` directory, recreating with `nix-shell` and deploying with krops or nixops.

**Comment by nixbitcoin** [comment]
I just now got this issue when updating my node and having the secrets files temporarily out of sync. My mistake was that I quit the `nix-shell` command prematurely because it was taking too long because of limited entropy on my system.

Try deleting your `~/my-nix-bitcoin/secrets` directory, recreating with nix-shell and deploying with krops or nixops.
